# Deliverable 3. Create a Travel Itinerary Map.
----
1. Import the vacation CSV file. 
2. From the map above with pick 4 cities that are in close proximity (on the same continent) that the customer would travel to and create a directions layer map.
3. For the "travel_mode" use either "DRIVING", "BICYCLING", or "WALKING".
4. Take a screenshot of the route and save it. 
5. Then create a marker layer for the four cities. Each city will should have a pop-up marker that contains
    - The hotel name
    - The city
    - The country
    - The current weather description and the maximum temperature
---

## Make sure the initial dependencies and the Google API key are imported.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

In [2]:
# Configure gmaps
gmaps.configure(api_key=g_key)

## From your `Vacation_Search` folder from Deliverable 2, import the `WeatherPy_vacation.csv` file as a DataFrame named `vacation_df`

In [3]:
# Read the WeatherPy_vacation.csv into a DataFrame
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_Vacation.csv")

# Display sample data
vacation_df.head(30)

,City_ID,City,Country,Max Temp,Lat,Lng,Hotel Name
0,0,Saint-Philippe,RE,81.10,-21.3585,55.7679,Le four Ã pain
1,9,Atuona,PF,76.23,-9.8000,-139.0333,Villa Enata
2,13,Vaini,TO,77.16,-21.2000,-175.2000,Keleti Beach Resort
3,14,Vanimo,PG,79.34,-2.6741,141.3028,Vahmoneh Lodge Vanimo
4,16,Luganville,VU,79.09,-15.5333,167.1667,The Espiritu Hotel
5,20,Bairiki,KI,82.40,1.3292,172.9752,Tarawa Boutique Hotel
6,30,Kloulklubed,PW,81.10,7.0419,134.2556,Storyboard Beach Resort
7,31,New Norfolk,AU,75.92,-42.7826,147.0587,The Shingles Riverside Cottages
8,35,Poum,NC,76.39,-20.2333,164.0167,NaN
9,37,Bandiagara,ML,85.33,14.3501,-3.6104,Hotel de la Falaise
10,38,Wum,CM,77.49,6.3833,10.0667,Wum Council Hall
11,46,Georgetown,MY,80.53,5.4112,100.3354,Cititel Penang
12,47,Kilindoni,TZ,79.56,-7.9139,39.6668,Bustani B&B
13,58,Xuddur,SO,87.85,4.1213,43.8894,Banjanay Hotel
14,59,Rafai,CF,85.71,4.9500,23.9167,NaN
15,62,Hobart,AU,76.26,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania
16,74,George Town,MY,80.53,5.4112,100.3354,Cititel Penang
17,76,Kapaa,US,75.52,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
18,81,Tamandare,BR,76.55,-8.7597,-35.1047,Pousada 100 Passos
19,82,Cape Town,ZA,78.12,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
20,88,Souillac,MU,80.98,-20.5167,57.5167,Shanti Maurice Resort & Spa
21,89,Alofi,NU,76.89,-19.0595,-169.9187,Taloa Heights
22,94,Gigmoto,PH,81.54,13.7796,124.3900,Cj's Travellers Inn
23,106,Maine-Soroa,NE,87.89,13.2114,12.0241,Complexe
24,111,Bathsheba,BB,81.21,13.2167,-59.5167,Atlantis Hotel
25,113,Puerto Escondido,MX,76.10,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
26,115,Kununurra,AU,84.18,-15.7667,128.7333,Hotel Kununurra
27,122,Phulabani,IN,78.73,20.4667,84.2333,Hotel Royal Plaza
28,124,Butaritari,KI,81.95,3.0707,172.7902,Isles Sunset Lodge
29,127,Champerico,GT,75.07,14.3000,-91.9167,"Hotel y restaurante ""El Diamante"""

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [4]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## In this step, you will set-up the pop-up markers. Review the code to create a marker layer map of the vacation search results. This code is the same as in Deliverable 2.

In [5]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [6]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

## From the vacation search map, *choose four cities* that a customer might want to visit. They should be close together and in the same country.

In [7]:
# Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df["City"] == "Emerald"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Emerald"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "New Norfolk"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Mount Isa"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Hobart"]

## Use the `to_numpy()` function and list indexing to write code to retrieve the latitude-longitude pairs as tuples from each city DataFrame.

In [8]:
# Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

## Use the [gmaps documentation](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#directions-layer) to create a directions layer map using the variables from the previous step. Where the starting and ending city are the same city, the `waypoints` are the three other cities, and the `travel_mode` is either `"DRIVING"`, `"BICYCLING"`, or `"WALKING"`.

In [9]:
# Define a new figure object
fig = gmaps.figure()

# Create a direction layer map using the start and end latitude-longitude pairs, and stop1, stop2, and stop3 as the waypoints.
# The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
vacation_itinerary = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')

# Add the layer to the map
fig.add_layer(vacation_itinerary)

# Display the map
fig

Figure(layout=FigureLayout(height='420px'))

## Use the provided `concat()` function code snippet to combine the four separate city DataFrames into one DataFrame.

In [10]:
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat(
    [
        vacation_start,
        vacation_stop1,
        vacation_stop2,
        vacation_stop3
    ],
    ignore_index = True
)

# Display sample data
itinerary_df

,City_ID,City,Country,Max Temp,Lat,Lng,Hotel Name
0,356,Emerald,AU,76.33,-23.5333,148.1667,Emerald Inn
1,31,New Norfolk,AU,75.92,-42.7826,147.0587,The Shingles Riverside Cottages
2,413,Mount Isa,AU,80.37,-20.7333,139.5000,ibis Styles Mt Isa Verona
3,62,Hobart,AU,76.26,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania

## Refactor the code from Step 6 to create a new marker layer map of the cities on the travel route.

In [11]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [12]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Define a new figure object
fig =  gmaps.figure()

# Add the layer to the map
fig.add_layer(marker_layer)

# Display the map
fig

Figure(layout=FigureLayout(height='420px'))